"""Add agent_runs table

Revision ID: 699751a0fd51
Revises: 0010_phase10_tkns
Create Date: 2026-03-29 08:47:43.064995
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '699751a0fd51'
down_revision = '0010_phase10_tkns'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_run_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('input_summary_hash', sa.String(), nullable=False),
    sa.Column('output_summary_hash', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_agent_name'), 'agent_runs', ['agent_name'], unique=False)
    op.drop_constraint(op.f('jobs_apply_url_key'), 'jobs', type_='unique')
    op.drop_constraint(op.f('refresh_token_sessions_token_hash_key'), 'refresh_token_sessions', type_='unique')
    op.alter_column('resume_profiles', 'raw_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('resume_profiles_user_id_key'), 'resume_profiles', type_='unique')
    op.drop_constraint(op.f('search_preferences_user_id_key'), 'search_preferences', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('search_preferences_user_id_key'), 'search_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('resume_profiles_user_id_key'), 'resume_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('resume_profiles', 'raw_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('refresh_token_sessions_token_hash_key'), 'refresh_token_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('jobs_apply_url_key'), 'jobs', ['apply_url'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_agent_runs_agent_name'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
