"""add_llm_usage_logs_table

Revision ID: d46c487e0236
Revises: 3b7c8ba1958f
Create Date: 2026-05-03 21:50:16.906503
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d46c487e0236"
down_revision = "3b7c8ba1958f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_usage_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_usage_logs_created_at"), "llm_usage_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_llm_usage_logs_model_name"), "llm_usage_logs", ["model_name"], unique=False)
    op.create_index(op.f("ix_llm_usage_logs_request_id"), "llm_usage_logs", ["request_id"], unique=False)
    op.create_index(op.f("ix_llm_usage_logs_user_id"), "llm_usage_logs", ["user_id"], unique=False)
    op.alter_column(
        "jobs",
        "external_id",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=2000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "external_id",
        existing_type=sa.String(length=2000),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_llm_usage_logs_user_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_request_id"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_model_name"), table_name="llm_usage_logs")
    op.drop_index(op.f("ix_llm_usage_logs_created_at"), table_name="llm_usage_logs")
    op.drop_table("llm_usage_logs")
    # ### end Alembic commands ###
